app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import Config
from .routes.personaje import personaje

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Bootstrap(app)

    app.register_blueprint(personaje)

    return app

app/routes/personaje.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.db import db 

personaje = Blueprint("personaje", __name__)

@personaje.route("/")
def index():
  personajes = db.character.find().sort('name',-1)

  return render_template("index.html",personajes=personajes)

@personaje.route('/character/<id>')
def get_character(id):
  
  p=db.character.find_one({'id':int(id)})
  print(p)

  return render_template('personaje.html',personaje=p)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block content %}

{% block scripts %} {{ super() }} {% endblock %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}

<h1>Rick and Morty Characters</h1>

<div class="row" style="margin-top: 30px">
  {% for personaje in personajes %}
  <div class="col-md-3">
    
    <div class="panel panel-default">

      <a href="{{ url_for('personaje.get_character', id= personaje['id']) }}">
      <div class="panel-body">
        <p>Name: {{ personaje['name'] }}</p>
        <p>Status: {{ personaje['status'] }}</p>
        <p>Specie: {{ personaje['species'] }}</p>
        <p>Ubicacion: {{ personaje['location']['name'] }} </p>
        <img src="{{ personaje['image'] }}" alt="" srcset="">
        
      </div>
      </a>
    </div>
  </div>

  {% endfor %}
</div>
{% endblock content %}

app/templates/personaje.html
{% extends "base.html" %}

{% block content %}
<h2><a href="/">HOME</a></h2>



<h1>Nombre: {{personaje['name']}}</h1>


<div class="col-md-5">
    <div class="panel panel-default">
        <div class="panel-body">
            <img src="{{ personaje['image'] }}" alt="" srcset="">
            <p>Status : {{ personaje['status'] }}</p>
            <p>Specie : {{ personaje['species'] }}</p>
            <p>Ubicacion : {{ personaje['location']['name'] }} </p>
            
            <p>Gender : {{ personaje['gender'] }}</p>
            <p>Origin : {{personaje['origin']['name']}}</p>
            <p>Type : {{ personaje['type'] }}</p>
            <p>Created at : {{ personaje['created'] }}</p>

        </div>
    </div>
    

</div>


{% endblock content %}